name: Run build on netlify

on:
  push:
    branches:
      - main

  schedule:
    # first day of the month at 2am
    - cron: '0 2 1 * *'

jobs:
  call_web:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f14903bd1a690c0d1fce14a